# Generated by Django 3.2 on 2023-08-28 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20230825_0613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(default='notset@gmail.com', max_length=254, verbose_name='email address'),
        ),
    ]
