# Generated by Django 3.2 on 2023-08-27 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20230825_0613'),
        ('researcher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='researcherprofile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='researcher', to='register.customuser'),
        ),
        migrations.AlterField(
            model_name='researcherprofile',
            name='usergroup',
            field=models.CharField(default='researcher', max_length=50),
        ),
    ]
