# Generated by Django 3.2 on 2023-09-01 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researcher', '0004_researcherprofile_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='researcherprofile',
            name='phone',
        ),
        migrations.AddField(
            model_name='researcherprofile',
            name='profile_is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
