# Generated by Django 3.2 on 2023-09-02 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_deviceauthmodel_devicenotificationtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawpost',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Paragraphs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paragraph', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rawpost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paragraphs', to='main.rawpost')),
            ],
        ),
    ]
