# Generated by Django 3.2 on 2023-09-06 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawpost',
            name='is_draft',
            field=models.BooleanField(default=True),
        ),
    ]
