# Generated by Django 3.2 on 2023-09-06 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('officer', '0006_officerprofile_physical_address'),
        ('main', '0006_rawpost_is_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawpost',
            name='saved_draft_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drafts', to='officer.officerprofile'),
        ),
    ]
