# Generated by Django 3.2 on 2023-08-27 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officer', '0002_alter_officerprofile_usergroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officerprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='officerprofile',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='officerprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='officerprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='officerprofile',
            name='usergroup',
            field=models.CharField(blank=True, default='officer', max_length=50, null=True),
        ),
    ]
